### ISSUE TITLE
timimi text 

### ISSUE THREAD

**Issue by drsnn** [ibnishak/Timimi#49] opened 2020-05-26 09:16 UTC
Hi Ibnishak 

First of all thank you for your extension. 

I try to installl to my mac (catalina 10-15) firefox but i couldnt do it. I installed firefox extension . But in the second step when  i dowload   timimi-2-1-1-Mac on my computer, it is opening with text.app and nothing running it just open a text file. Where i am doing wrong. Thank you very much.

>Download timimi-2-1-1-Mac from Github . Run it by double clicking [If your OS asks for confirmation, choose "Run"]. Select the appropriate browser when asked.>

**Comment by ibnishak** [comment] 2020-05-26 09:20
Can you open the terminal application in Mac and run the following commands

```
cd ~/Downloads
chmod +x ./timimi-2-1-1-Mac
./timimi-2-1-1-Mac
```

**Comment by drsnn** [comment] 2020-05-26 09:59
Thank you very much Ibnishak. I solved problem. I hope it will support Safari because most mac user Safari. Thanks very much again

**Comment by ibnishak** [comment] 2020-05-26 20:51
Safari support is a milestone, albeit a distant one owing to the incompatibilities with other browser extension APIs.

Given that the issue is solved, would you consider closing this issue?

**Closed** 2020-05-26 21:47 UTC
